micronaut:
  application:
    name: reportConnector
  server:
    port: ${APPLICATION_SERVER_PORT:7788}
  metrics:
    enabled: true
    export:
      prometheus:
        enabled: true
        descriptions: true
        step: PT1M

