micronaut:
  application:
    name: connector
  server:
    port: ${APPLICATION_SERVER_PORT:7788}
  metrics:
    enabled: true
    export:
      prometheus:
        enabled: true
        descriptions: true
        step: PT1M

#datasources:
#  default:
#    url: "jdbc:mysql://localhost:3306/observertc3?serverTimezone=EET&useLegacyDatetimeCode=false"
#    username: root
#    password: "password"
#    driverClassName: com.mysql.cj.jdbc.Driver